### ISSUE TITLE
"Open with" context menu showing multiple MacVim entries

### ISSUE THREAD

**Issue by dexrualo** [macvim-dev/macvim#569]
When opening a context menu (right clicking MacVim associated files) and selecting the "Open with" entry, multiple MacVim entries are showing with past version numbers.

**Comment by chdiza** [comment]
This is not MacVim's fault.  Your launchservices database thinks there are multiple versions of MacVim on your machine.  If you have older versions of MacVim.app hanging around, delete them.
Sometimes launchservices gets confused about which apps are present and doesn't "forget" the older versions of MacVim.

If there's only one version of MacVim on your machine, doing
```
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user
```
should fix it.

**Comment by dexrualo** [comment]
You are right. Upon checking the /usr/local/Cellar/macvim directory, previous versions of the app still existed. I just assumed Homebrew deleted them upon upgrading. I did a `brew cleanup` and the problem was solved. Thanks!
