### ISSUE TITLE
Rows of text seem clipped at certain font sizes on Catalina

### ISSUE THREAD

**Issue by twk** [macvim-dev/macvim#905]
Running 8.1.950 on Catalina, when I start MacVim, some lowercase letters are getting clipped:

![image](https://user-images.githubusercontent.com/15460/59234645-9f97cf80-8ba2-11e9-9e81-501c897ea206.png)

If I adjust the font size and then adjust it back, things are rendered correctly:

![image](https://user-images.githubusercontent.com/15460/59234683-c8b86000-8ba2-11e9-8e0d-ada16dd34bd2.png)

This started as soon as I upgraded to Catalina -- Mojave was fine.  My font settings are English/Menlo/Regular/11

**Comment by ychin** [comment]
I will need to see if I can repro this under the new Xcode. Otherwise could be tricky as I don't have a beta Catalina install with me.

**Comment by AdamJacobMuller** [comment]
Happens for me, but, only with Core Text renderer enabled.

With Core Text renderer disabled things are actually considerably worse.

<img width="227" alt="image" src="https://user-images.githubusercontent.com/623767/59477921-69b64d80-8e25-11e9-87d5-3bd01693885c.png">
actual:
<img width="188" alt="image" src="https://user-images.githubusercontent.com/623767/59477930-78046980-8e25-11e9-81b7-2588d1d975fc.png">

**Comment by eirnym** [comment]
I'd wait for first public beta. Before that point macOS is not really usable at all

**Comment by AdamJacobMuller** [comment]
Aside from the MacVim issue my workflow is fine and I've just been running `vim` instead.

**Comment by eirnym** [comment]
I'm really surprised to read it! This release will be the first one with relatively stable betas, since it wasn't a case since macOS 10.7 Beta 1

**Comment by eirnym** [comment]
Public Beta is out…

**Comment by eirnym** [comment]
It's interesting, I can reproduce it with 

`guifont=Menlo-Regular:h11`, but not with `guifont=Fira\ Code\ Light:h12`
```

**Comment by jjgod** [comment]
This is a duplicate of #883.

**Comment by jjgod** [comment]
Oh, @eirnym, it's because the comparison sees that the new font `Menlo-Regular:h11` is the same  as the default font initialized by `-[MMCoreTextView initWithFrame:]` and skip rest of the initialization:

    if (!(newFont && font != newFont))
        return;

That's why in this case `fontDescent` is still properly initialized.

**Comment by jjgod** [comment]
(lldb) p font
	(NSCTFont *) $0 = 0x0000000101c233e0
	(lldb) p newFont
	(NSCTFont *) $1 = 0x0000000101c233e0
	(lldb) po font
	"Menlo-Regular 11.00 pt. P [] (0x101c28300) fobj=0x101c233e0, spc=6.62"

	(lldb) po newFont
	"Menlo-Regular 11.00 pt. P [] (0x101a00860) fobj=0x101c233e0, spc=6.62"

**Comment by eirnym** [comment]
I've tried it after Fira Code, to guarantee that it's a different one

**Comment by jjgod** [comment]
That's why you are not hitting the problem with Fira Code.

**Comment by eirnym** [comment]
and what's about Menlo?

I've set Fira Code first, then Menlo, and issue still exists. This doesn't neglect your issue on `fontDescent`, though. Probably, in macOS Catalina this parameter becomes more valuable to set if it's not.

**Comment by jjgod** [comment]
How exactly did you do that? Did you execute multiple `set guifont` command?

**Comment by ychin** [comment]
I think this should now be fixed and will be released in the next update. If someone wants to confirm (I haven't installed the beta macOS yet) that would be great.

**Comment by eirnym** [comment]
I'll test it today

**Comment by AdamJacobMuller** [comment]
i'm happy to test but i don't particularly want to build this myself and it seems like the last release was 157, any chance of 158 being released to test?

**Comment by tobireif** [comment]
I just installed MacOS Catalina (version "10.15 (19A583)"). Now I get this issue:
<img width="590" alt="screenshot" src="https://user-images.githubusercontent.com/80411/66403052-3441fb00-e9e6-11e9-860c-0c1c50c3aaff.png">
MacVim version "Custom Version 8.1.1722 (157)".
This is a severe issue. I hope it can get fixed soon.

**Comment by securitygeneration** [comment]
I'm also surprised this wasn't fixed/released prior to Catalina's release.

**Comment by eirnym** [comment]
@securitygeneration This is an open source project. You could do a contribution of your time and knowledge.

**Comment by securitygeneration** [comment]
@eirnym I was following this and saw that it seemed to be tentatively resolved (https://github.com/macvim-dev/macvim/issues/905#issuecomment-516080155), and so it didn't seem to need any additional attention (although yes, I could've tried to test it).  ¯\_(ツ)_/¯

**Comment by ychin** [comment]
Next update will be out this weekend.

**Comment by hoke-t** [comment]
Any updates on this?

**Comment by isaki** [comment]
As per @eirnym, I am posting this here and closing my issue.

I can confirm this is still an issue after the weekend.

I am running the latest release:
![image](https://user-images.githubusercontent.com/10616227/66783245-83d06d00-eea5-11e9-8755-d4b6f0ac5afa.png)

And can confirm fonts still look strange:
![image](https://user-images.githubusercontent.com/10616227/66783290-9c408780-eea5-11e9-8dec-6a07b4c5999e.png)

And that the changing the font size back and forth fixes things:
![image](https://user-images.githubusercontent.com/10616227/66783356-bc704680-eea5-11e9-9ca2-ca4d4bb366e7.png)

My macOS version:
```
% sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A583
```

**Comment by eirnym** [comment]
@isaki Thank you for an addition, Please, write which distribution of MacVim do you use (e.g. GitHub, Homebrew, MacPorts, etc) and which font are you using

**Comment by tobireif** [comment]
> changing the font size back and forth fixes things

Here it fixes it temporarily for that one buffer/window, but not permanently.

(I'm using the distribution from https://github.com/macvim-dev/macvim/releases plus auto-updates.)

`:set guifont?` says `guifont=Menlo:h16`

**Comment by hoke-t** [comment]
I have the exact issue as well. I always have to increase and then decrease the font size upon opening a file to fix the clipping.

Using macOS 10.15 build version 19A583, Homebrew distribution of MacVim, and `set guifont?` gives `guifont=Menlo-Regular:h11`.

**Comment by isaki** [comment]
@eirnym I am using the GitHub distribution of MacVim.

I apparently have no font set once so ever:
![image](https://user-images.githubusercontent.com/10616227/66844371-36530f00-ef3c-11e9-9c0f-47e4bfb05272.png)

Also, commands are also being chopped off:
![image](https://user-images.githubusercontent.com/10616227/66844443-4e2a9300-ef3c-11e9-8318-6e9c13d32bc5.png)

Finally, this is the font setup that seems to be in use when I run `set guifont=*`:
![image](https://user-images.githubusercontent.com/10616227/66844507-639fbd00-ef3c-11e9-805b-f40bec83de2d.png)

I hope this information helps!

**Comment by eirnym** [comment]
Thank you, this is fixed in `HEAD`. So I hope @ychin will find the time to prepare a release.

**Comment by jimsiff** [comment]
Thank you @eirnym and @ychin.  It's fixed for me after building 8.1.2102 on Catalina.

**Comment by ychin** [comment]
This should be fixed in snapshot-159. Let me know if it isn't.

**Comment by isaki** [comment]
This has indeed fixed it, thank you!

**Comment by hoke-t** [comment]
Can confirm as well. Thanks!
